apiVersion: apps/v1
kind: Deployment
metadata:
  name: battleships
spec:
  replicas: 2
  selector:
    matchLabels:
      app: battleships
  template:
    metadata:
      labels:
        app: battleships
    spec:
      containers:
      - name: battleships
        image: battleships:  # Example Jenkins build number
        ports:
        - containerPort: 3000
