pipeline {
    agent any
    environment {
        DOCKER_IMAGE = "battleships"
        BUILD_TAG = "${BUILD_NUMBER}"
    }
    stages {
        stage('Set Minikube Docker Daemon') {
            steps {
                sh 'eval $(minikube docker-env)'  // Use Minikube's Docker daemon
            }
        }
        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${DOCKER_IMAGE}:${BUILD_TAG} ."
                sh "docker tag ${DOCKER_IMAGE}:${BUILD_TAG} ${DOCKER_IMAGE}:latest"  // Optional: Use "latest"
            }
        }
        stage('Apply Kubernetes Deployment') {
            steps {
                sh 'kubectl apply -f battleships-deployment.yaml'
            }
        }
    }
}
