apiVersion: apps/v1
kind: Deployment
metadata:
  name: battleships
spec:
  replicas: 2
  selector:
    matchLabels:
      app: battleships
  template:
    metadata:
      labels:
        app: battleships
    spec:
      containers:
      - name: battleships
        image: battleships  # Example Jenkins build number
        imagePullPolicy: Never  # Ensures Kubernetes uses the locally built image
        ports:
        - containerPort: 3000
