apiVersion: v1
kind: Service
metadata:
  name: battleships-service
spec:
  selector:
    app: battleships
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
